#!/sbin/busybox sh

cd /sbin

for i in $(./busybox --list)
do
	./busybox ln -s busybox $i
done

cd /

mount -t proc proc /proc
mount -t sysfs sysfs /sys

umount -f /system
umount -f /data

chmod 755 /init
chmod 644 /*.n1
chmod 644 /*.rc
chmod 644 /*.prop

rm /init
mv -f /res/ramdisks/custom/* /

exec /init
exit

mkdir /dev
mkdir /dev/block
mknod /dev/block/platform/msm_sdcc.1/by-name/system b 179 24
mknod /dev/block/platform/msm_sdcc.1/by-name/userdata b 179 25
mount -t ext4 /dev/block/platform/msm_sdcc.1/by-name/system /system
mount -t ext4 /dev/block/platform/msm_sdcc.1/by-name/userdata /data
